language: common-lisp
sudo: false

addons:
  apt:
    packages:
    - zip
env:
  global:
  - GAMEKIT_SYSTEM_NAME: sih
  - GAMEKIT_APPLICATION_PACKAGE: sih
  - GAMEKIT_APPLICATION_MAIN_CLASS: game
  - PATH: ~/.bodge/bin/:$PATH
  - GAMEKIT_TARGET_PACKAGE: "$GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip"
  - GAMEKIT_BUILD_DIR: "/tmp/$GAMEKIT_SYSTEM_NAME"
  - secure: IGU7FYXAtRy2yYcizHB+5V9aRSDLKuZ0KUm9ZSYPbUWhMrqArDgyQxUJFI6FHzUN3ichd4yp/oshaQ6qjn5DwyTgAQU8AF5UC2z6Anyi8IA5RSPRmnTodn4jyv7NP0jehV4hK7QHmCC4B1Hynz3siUmwVwFRHPJmx8JnMq3odUismUUK9vrr/uuts9DAEsB335tPYW3k8VwokU5mGu2hyz8SQ3L4Hpq2gGOMU2QNaPncabggiOgsItEcaHP5RCn0/r0DPddRClDMUPmtGye79XKO2THk1nrvFp6avf7WLSBagV7K/4OBB7tWlWWFBnQxOuILLUTPmFso4DTmk0SMT6v1THZGDjgOVZ+cU/UhmREc8fHRxD5f3z7c54CoAtOSA21YzBm/A2WPkzciUXKCd7i78FQu0pAUwHEAqpclhHlYEvcDAOJ0nvIVY23PHGvprWhxIAFd/bN5RnF26U4sJFT2zFs1YR7Qh07O2Jer/PBe5cmFNrrOnkN8ONvEzylWPVBJ8ETiIWADKoEUNR/ym+b2bQ/mTNemTfTuuC3PhMKUYVzYOArroDSpvhFU6TXVguBDX9u+uqgKzDDCwSbfdiUJtFpAknhdc8B1fnVVczr7807JBA9g62vVYKRmUtFSpAn//tDTH/xMhDFc2DhG6BIedSZzrrO9CUKEu/kIrXk=

branches:
  only:
  - "/^v\\d+(\\.\\d+)+$/"

os:
- linux
- osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - curl -L http://bodge.borodust.org/files/install.sh | sh
  - git lfs install && git lfs pull
  - lisp install-dist

script:
  - >
    lisp build-gamekit-system
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR

before_deploy:
- mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: "$GITHUB_TOKEN"
  file: "$GAMEKIT_TARGET_PACKAGE"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
